apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: wazi-codeready-operator-group
  namespace: {{ .Values.namespace }} 
  annotations:
    argocd.argoproj.io/sync-wave: "100" 
spec:
  targetNamespaces:
  - {{ .Values.namespace }}  